var data = [{
  'type': 'hospital',
  'name': 'Hospital Arzobispo Loayza',
  'image': '../assets/images/hospital1.jpg',
  'address': 'Avenida Alfonso Ugarte 848, Cercado de Lima 15082',
  'clock': '8:00 am. - 17:00 pm',
  'cellphone':'(01) 6144646',
},
{
  'type': 'clinica',
  'name': 'Clínica Porvenir',
  'image': '../assets/images/clinica1.jpg',
  'address': 'Jesús María, 18, Avenida Mariategui 1418, Cercado de Lima 15072',
  'clock': '24:00 horas',
  'cellphone':'(01) 6528282',
},
{
  'type': 'hospital',
  'name': 'Hospital Nacional Dos De Mayo',
  'image': '../assets/images/hospital2.jpg',
  'address': ' Av. Miguel Grau 13, Cercado de Lima 15003',
  'clock': '24:00 horas',
  'cellphone':' (01) 3280028',
},
{
  'type': 'clinica',
  'name': 'Clínica Anglo Americana',
    'image': '../assets/images/clinica2.jpg',
  'address': ' Calle Alfredo Salazar 350, San Isidro 15073',
  'clock': '24:00 horas',
  'cellphone':'(01)6168900',
},
{
  'type': 'hospital',
  'name': 'Hospital de Emergencias Grau',
  'image': '../assets/images/hospital3.jpg',
  'address': 'Grau 351, Cercado de Lima 15001',
  'clock': '24:00 horas',
  'cellphone':' (01) 4118000',
},
{
  'type': 'clinica',
  'name': 'Clinica Limatambo',
  'image': '../assets/images/clinica3.jpg',
  'address': ' Av. República de Panamá 3606, San Isidro 15047',
  'clock': '24:00 horas',
  'cellphone':'(01) 6171111',
},
{
  'type': 'hospital',
  'name': 'Hospital Edgardo Rebagliati Martins',
  'image': '../assets/images/hospital4.jpg',
  'address': 'Av Edgardo Rebagliati 490, Jesús María 15072',
  'clock': '6:00 am. - 23:00 pm',
  'cellphone':' (01) 2654901',
},
{
  'type': 'clinica',
  'name': 'Clinica Internacional, Sede San Borja',
  'image': '../assets/images/clinica4.jpg',
  'address': 'Av. Guardia Civil 385, Cercado de Lima 15036',
  'clock': '7:00 am. - 20:00 pm',
  'cellphone':'(01)6196161',
},
{
  'type': 'hospital',
  'name': 'Hospital Víctor Larco Herrera',
  'image': '../assets/images/hospital5.jpg',
  'address': 'Av. del Ejército 600, Magdalena del Mar 15076',
  'clock': '24:00 horas',
  'cellphone':'(01) 2615516',
},
{
  'type': 'clinica',
  'name': 'Clínica Santa Isabel ',
  'image': '../assets/images/clinica5.jpg',
  'address': ' Av. Guardia Civil 135, Cercado de Lima 41',
  'clock': '8:00 am. - 21:00 pm',
  'cellphone':'(01)  4174100',
}];
